"""Generate the method comparison appendix from actual benchmark outputs."""
from pathlib import Path
from decimal import Decimal,localcontext,ROUND_CEILING
import json,re,pandas as pd
ROOT=Path(__file__).resolve().parents[1];OUT=ROOT/'output'
report=json.loads((OUT/'quota-benchmarks.json').read_text());rows=report['rows']

def upward(x):
    with localcontext() as ctx:
        ctx.prec=80;ctx.rounding=ROUND_CEILING
        return str(Decimal.from_float(x).quantize(Decimal('.001')))

labels={('quota','shared',True):'Quota, shared event',('quota','separate',True):'Quota, individual tests',
        ('quota','shared',False):'Quota, shared, no bin floors',('hoeffding_baseline_optimized','shared',True):'Hoeffding, shared',
        ('serfling_baseline_optimized','shared',True):'Serfling, shared',('harmonic_martingale_baseline_optimized','shared',True):'Harmonic martingale, shared'}
table=['\\begin{tabular}{lrr}\n\\toprule\nMoment/event & Mean loss & Shortfall loss\\\\\n\\midrule\n']
values={}
for key,label in labels.items():
    rr={x['objective']:x['fixed_proposal_loss_upper'] for x in rows if (x['moment_method'],x['event'],x['bin_floors'])==key}
    table.append(label+' & '+upward(rr['mean'])+' & '+upward(rr['shortfall_6'])+'\\\\\n');values[key]=rr
table.append('\\bottomrule\n\\end{tabular}\n')
(OUT/'tables/quota_method_comparison.tex').write_text(''.join(table),encoding='utf8',newline='\n')
design=json.loads((OUT/'quota-design-benchmarks.json').read_text())['rows']
table=['\\begin{tabular}{rlrrr}\n\\toprule\nQuota & Weights & Quota radius & Harmonic radius & Reduction (\\%)\\\\\n\\midrule\n']
for row in design:
    if row['n']!=12:continue
    table.append(f"{row['k']} & {row['weight_shape'].capitalize()} & {row['quota_radius']:.3f} & {row['harmonic_martingale_radius']:.3f} & {100*(1-row['quota_over_martingale']):.2f}"+'\\\\\n')
table.append('\\bottomrule\n\\end{tabular}\n')
(OUT/'tables/quota_design_comparison.tex').write_text(''.join(table),encoding='utf8',newline='\n')
macro={'ClassicalMeanCertificate':upward(values[('harmonic_martingale_baseline_optimized','shared',True)]['mean']),
       'ClassicalShortfallCertificate':upward(values[('harmonic_martingale_baseline_optimized','shared',True)]['shortfall_6']),
       'SeparateQuotaMeanCertificate':upward(values[('quota','separate',True)]['mean']),
       'SeparateQuotaShortfallCertificate':upward(values[('quota','separate',True)]['shortfall_6'])}
(ROOT/'paper/quota-comparison-results.tex').write_text('% Generated by code/build_quota_comparison_exhibits.py.\n'+''.join('\\newcommand{\\'+k+'}{'+v+'}\n' for k,v in macro.items()),encoding='utf8',newline='\n')
(OUT/'quota-comparison-numbers.json').write_text(json.dumps(macro,indent=2)+'\n',encoding='utf8')
mapping=pd.read_csv(ROOT/'docs/output-map.csv');records=[]
builder_lines=(ROOT/'code/build_quota_comparison_exhibits.py').read_text(encoding='utf8').splitlines()
for name,leaf in [('Existing-method comparison','quota_method_comparison'),('Representative quota designs','quota_design_comparison')]:
    records.append({'exhibit':name,'generated_file':'output/tables/'+leaf+'.tex','builder':'code/build_quota_comparison_exhibits.py',
                    'builder_line':next(i for i,line in enumerate(builder_lines,1) if "(OUT/'tables/"+leaf+".tex')" in line),
                    'estimator':'code/quota_benchmarks.py' if leaf=='quota_method_comparison' else 'code/benchmark_quota_designs.py',
                    'numerical_source':'quota-benchmarks.json' if leaf=='quota_method_comparison' else 'quota-design-benchmarks.json'})
records.append({'exhibit':'Quota comparison in-text numbers','generated_file':'paper/quota-comparison-results.tex','builder':'code/build_quota_comparison_exhibits.py',
                'builder_line':next(i for i,line in enumerate(builder_lines,1) if "(ROOT/'paper/quota-comparison-results.tex')" in line),
                'estimator':'code/quota_benchmarks.py','numerical_source':'quota-comparison-numbers.json'})
new=pd.DataFrame(records)
mapping=pd.concat([mapping[~mapping.generated_file.isin(new.generated_file)],new],ignore_index=True)
text=(ROOT/'paper/paper.tex').read_text(encoding='utf8')
for i,block in enumerate(re.findall(r'\\begin\{table\}.*?\\end\{table\}',text,flags=re.S),1):
    match=re.search(r'output/tables/([^}]+)',block)
    if match:mapping.loc[mapping.generated_file=='output/tables/'+match[1],'exhibit']='Table '+str(i)
mapping.to_csv(ROOT/'docs/output-map.csv',index=False,lineterminator='\n')
print('Generated two method comparison tables and four macros')
