"""Parent bridge and joint uncertainty exhibits for the first JDE revision."""
from pathlib import Path
import json,re
import pandas as pd

ROOT=Path(__file__).resolve().parents[1];OUT=ROOT/'output'

def table(name,head,rows):
    lines=['\\begin{tabular}{l'+'r'*(len(head)-1)+'}\n\\toprule\n',
           ' & '.join(head)+'\\\\\n\\midrule\n']
    lines += [' & '.join(row)+'\\\\\n' for row in rows]
    lines+=['\\bottomrule\n\\end{tabular}\n']
    (OUT/'tables'/name).write_text(''.join(lines),encoding='utf8',newline='\n')

def main():
    bridge=pd.read_csv(OUT/'population_parent_crosswalk.csv')
    cross=pd.read_csv(OUT/'community_cross_stratum.csv');cash=pd.read_csv(OUT/'community_cash_pairs.csv')
    reconstruction=json.loads((OUT/'population-crosswalk.json').read_text())
    labels={'source_pooled_controls':'Source score; pooled small cash',
            'source_split_controls':'Source score; split cash',
            'source_split_common':'Source score; common identified sample',
            'item_split_common':'Item score; same common sample',
            'item_split_controls':'Item score; available sample',
            'item_split_lag_complete':'Item score; lag control only',
            'complete_module_split_lag':'Complete modules; lag control only'}
    rows=[]
    for key,label in labels.items():
        s=bridge[bridge.stage.eq(key)].set_index('arm')
        rows.append([label,str(int(s.iloc[0].N)),*[f'{s.loc[a,"effect"]:.3f}' for a in ['Gikuriro','Lower','Middle','Upper','Large']]])
    table('population_parent_bridge.tex',['Corrected-release specification','N','GK','Lower','Middle','Upper','Large'],rows)
    labels={'assignment_weighted_ratios':'Block ratios','block_wls':'Block WLS','baseline_ancova':'Baseline ANCOVA'}
    rows=[];macros={}
    for estimator,label in labels.items():
        for policy in ['Lower+Large','Upper']:
            r=cross[cross.estimator.eq(estimator)&cross.cost_convention.eq('cost_eligible')&cross.policy.eq(policy)].iloc[0]
            rows.append([label+'; GK minus '+('lower/large' if policy=='Lower+Large' else 'upper'),f'{r.estimate:.3f}',f'{r.se:.3f}',f'{r.p:.3f}',f'{r.p_holm:.3f}'])
            if policy=='Lower+Large':
                prefix={'assignment_weighted_ratios':'Ratio','block_wls':'WLS','baseline_ancova':'ANCOVA'}[estimator]
                macros['Cross'+prefix+'Estimate']=f'{r.estimate:.3f}'
                macros['Cross'+prefix+'Holm']=f'{r.p_holm:.3f}'
    table('population_cross_stratum.tex',['Ineligible minus eligible contrast','Difference','Joint SE','Pointwise $p$','Holm $p$'],rows)
    rows=[]
    for estimator,label in labels.items():
        for population in ['eligible','baseline_weight_aggregate']:
            r=cash[cash.estimator.eq(estimator)&cash.cost_convention.eq('cost_eligible')&cash.left.eq('Upper')&cash.right.eq('Lower+Large')&cash.population.eq(population)].iloc[0]
            rows.append([label+'; '+('eligible' if population=='eligible' else 'aggregate'),f'{r.estimate:.3f}',f'{r.se:.3f}',f'{r.p:.3f}',f'{r.p_holm:.3f}'])
    table('population_cash_uncertainty.tex',['Upper minus lower/large cash','Difference','Joint SE','Pointwise $p$','Holm $p$'],rows)
    linear=reconstruction['linear_population_cost_reconstruction']
    macros['PopulationLinearGKDifference']=f'{linear["gikuriro_minus_cost_equivalent_cash"]:.3f}'
    macros['PopulationLinearGKSE']=f'{linear["village_se"]:.3f}'
    source=bridge[bridge.stage.eq('source_split_controls')].set_index('arm')
    macros['PopulationSourceGKUpper']=f'{source.loc["Gikuriro","effect"]-source.loc["Upper","effect"]:.3f}'
    (ROOT/'paper/population-revision-results.tex').write_text('% Generated by code/build_population_revision_exhibits.py\n'+''.join('\\newcommand{\\'+k+'}{'+v+'}\n' for k,v in macros.items()),encoding='utf8',newline='\n')
    (OUT/'population-revision-numbers.json').write_text(json.dumps(macros,indent=2)+'\n',encoding='utf8',newline='\n')
    files=['output/tables/population_parent_bridge.tex','output/tables/population_cross_stratum.tex',
           'output/tables/population_cash_uncertainty.tex','paper/population-revision-results.tex']
    mapping=pd.read_csv(ROOT/'docs/output-map.csv');records=[]
    own=Path(__file__).read_text().splitlines()
    for file in files:
        records.append({'exhibit':'Population revision','generated_file':file,'builder':'code/build_population_revision_exhibits.py',
                        'builder_line':next(i for i,line in enumerate(own,1) if Path(file).name in line),
                        'estimator':'code/population_crosswalk.py; code/population_uncertainty.py',
                        'numerical_source':'population_parent_crosswalk.csv; community_cross_stratum.csv; community_cash_pairs.csv'})
    mapping=pd.concat([mapping[~mapping.generated_file.isin(files)],pd.DataFrame(records)],ignore_index=True)
    text=(ROOT/'paper/paper.tex').read_text(encoding='utf8')
    for i,block in enumerate(re.findall(r'\\begin\{table\}.*?\\end\{table\}',text,flags=re.S),1):
        match=re.search(r'output/tables/([^}]+)',block)
        if match:mapping.loc[mapping.generated_file=='output/tables/'+match[1],'exhibit']='Table '+str(i)
    mapping.to_csv(ROOT/'docs/output-map.csv',index=False,lineterminator='\n')
    print('Generated parent bridge, cross-stratum and cash uncertainty tables')

if __name__=='__main__':main()
